import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { CostByRoleChart } from "@/components/finance/cost-by-role-chart"
import { CostVsRevenueChart } from "@/components/finance/cost-vs-revenue-chart"
import { FinancialOverviewChart } from "@/components/finance/financial-overview-chart"
import { RevenueBreakdownChart } from "@/components/finance/revenue-breakdown-chart"
import { CostDistributionChart } from "@/components/finance/cost-distribution-chart"

export default function FinancePage() {
  return (
    <div className="w-full max-w-7xl mx-auto px-4 md:px-6 space-y-6">
      <div className="flex flex-col gap-2">
        <h1 className="text-2xl font-bold tracking-tight">Financial Dashboard</h1>
        <p className="text-muted-foreground">
          Track financial performance, revenue streams, and cost distribution across your projects.
        </p>
      </div>

      <Tabs defaultValue="overview" className="w-full">
        <TabsList className="mb-4">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="revenue">Revenue</TabsTrigger>
          <TabsTrigger value="costs">Costs</TabsTrigger>
          <TabsTrigger value="profitability">Profitability</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-6">
          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Financial Overview</CardTitle>
              <CardDescription>Monthly revenue, expenses, and profit trends</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[400px]">
                <FinancialOverviewChart />
              </div>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="shadow-sm">
              <CardHeader>
                <CardTitle>Revenue Breakdown</CardTitle>
                <CardDescription>Revenue by service category</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[350px]">
                  <RevenueBreakdownChart />
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-sm">
              <CardHeader>
                <CardTitle>Cost Distribution</CardTitle>
                <CardDescription>Quarterly cost breakdown by category</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[350px]">
                  <CostDistributionChart />
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="revenue" className="space-y-6">
          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Revenue Trends</CardTitle>
              <CardDescription>Monthly revenue by project type</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[400px]">
                <FinancialOverviewChart />
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Revenue by Service</CardTitle>
              <CardDescription>Detailed breakdown of revenue sources</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[400px]">
                <RevenueBreakdownChart />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="costs" className="space-y-6">
          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Cost by Role</CardTitle>
              <CardDescription>Distribution of costs across different roles</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[400px]">
                <CostByRoleChart />
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Cost Distribution</CardTitle>
              <CardDescription>Breakdown of costs by category</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[400px]">
                <CostDistributionChart />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="profitability" className="space-y-6">
          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Cost vs Revenue by Staff</CardTitle>
              <CardDescription>Compare cost and revenue generated by each team member</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[400px]">
                <CostVsRevenueChart />
              </div>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="shadow-sm">
              <CardHeader>
                <CardTitle>Profit Margin Trends</CardTitle>
                <CardDescription>Monthly profit margin percentage</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[350px]">
                  <FinancialOverviewChart />
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-sm">
              <CardHeader>
                <CardTitle>Project Profitability</CardTitle>
                <CardDescription>Profit margin by project</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[350px]">
                  <RevenueBreakdownChart />
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  )
}
